name: "spark-multinode-stack"

x-spark-common: &spark-common
  image: apache/spark:3.5.1
  volumes:
    - ./jobs:/opt/spark/work-dir/jobs
    - ./data:/opt/spark/work-dir/data
  command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  depends_on:
    - spark-master
  environment:
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_MASTER: spark://spark-master:7077
  networks:
    - spark-multinode-network

services:
  spark-master:
    image: apache/spark:3.5.1
    volumes:
      - ./jobs:/opt/spark/work-dir/jobs
      - ./data:/opt/spark/work-dir/data
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
    networks:
      - spark-multinode-network

  spark-worker-1:
    <<: *spark-common
  spark-worker-2:
    <<: *spark-common
  spark-worker-3:
    <<: *spark-common
  spark-worker-4:
    <<: *spark-common

networks:
  spark-multinode-network:
    driver: bridge
